### ISSUE TITLE
(Cenizas) Desarrollo de integración MP - Enternet

### ISSUE THREAD

**Issue by AntaraGithub** [AntaraGithub/Antara5#4]

**Comment by sebastian-baltazar** [comment]
Se finaliza desarrollo de integración hacia Enternet con el objetivo de obtener información de la GDE, es decir, su folio y el documento que se obtiene. 

Se actualiza el ambiente de desarrollo de azure para incluir la API que permite la comunicación entre la web de Antara y el servicio de Enternet

**Comment by FelipeSotoPedrero** [comment]
Se revisa la integración hacia Enternet con el objetivo de obtener información de la GDE, es decir, su folio y el documento .
Se crean Guías de despacho y se descarga el documento para validar información contenida en él, sea fidedigna.
